In [12]:
import pickle

with open("data/opendata/normal_LsideSegm_28markers.pkl","rb") as f:
    data_nomarl=pickle.load(f)
with open("data/opendata/stroke_NsideSegm_28markers.pkl","rb") as f:
    data_stroke=pickle.load(f)

/tmp/ipykernel_72168/1229705775.py:4: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  data_nomarl=pickle.load(f)
/tmp/ipykernel_72168/1229705775.py:6: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case

In [13]:
data_nomarl.keys()

dict_keys(['data', 'n_trials', 'marker_names', 'subject_ids'])

In [14]:
type(data_nomarl['data'])

list

In [15]:
len(data_nomarl['data']),data_nomarl['n_trials'],data_nomarl['marker_names'],len(data_nomarl['subject_ids'])

(138,
 array([ 7,  9,  4,  6, 13,  8,  5,  9,  6,  7, 10,  5, 10,  4,  7,  4,  6,
         7,  6,  6,  9,  9,  5,  8,  7,  8,  9,  8,  4,  4,  3,  8,  9,  6,
         6,  6,  4,  4,  6,  5,  6,  8,  5,  6,  5,  3,  6,  3,  6,  7,  5,
         6,  8,  3,  5,  8,  6,  3,  6,  7,  5,  6,  7,  5,  6,  8,  8,  8,
         5,  5,  7,  3,  7,  4,  6,  6,  8,  7,  5,  6,  6,  5,  9,  6,  6,
         6,  8,  6,  4, 12,  7,  4,  6,  8,  5,  5,  4,  8,  6,  5,  6,  5,
         6,  3,  9,  6,  8,  4,  6,  5,  5,  4,  4,  3,  6,  8,  5,  5,  3,
         3,  7,  2,  4,  4,  5,  7,  3,  3,  4, 11,  4,  4,  5,  4,  7,  4,
         4,  5]),
 ['C7',
  'T10',
  'CLAV',
  'STRN',
  'L_ASI',
  'L_SHO',
  'L_ELB',
  'L_WRA',
  'L_WRB',
  'L_FIN',
  'L_THI',
  'L_KNE',
  'L_TIB',
  'L_ANK',
  'L_HEE',
  'L_TOE',
  'R_ASI',
  'R_SHO',
  'R_ELB',
  'R_WRA',
  'R_WRB',
  'R_FIN',
  'R_THI',
  'R_KNE',
  'R_TIB',
  'R_ANK',
  'R_HEE',
  'R_TOE'],
 138)

In [16]:
type(data_nomarl['data'][0])

numpy.ndarray

In [17]:
import numpy as np
for p_data in data_nomarl["data"]:
    print(np.shape(p_data))



(28, 7, 1001, 3)
(28, 9, 1001, 3)
(28, 4, 1001, 3)
(28, 6, 1001, 3)
(28, 13, 1001, 3)
(28, 8, 1001, 3)
(28, 5, 1001, 3)
(28, 9, 1001, 3)
(28, 6, 1001, 3)
(28, 7, 1001, 3)
(28, 10, 1001, 3)
(28, 5, 1001, 3)
(28, 10, 1001, 3)
(28, 4, 1001, 3)
(28, 7, 1001, 3)
(28, 4, 1001, 3)
(28, 6, 1001, 3)
(28, 7, 1001, 3)
(28, 6, 1001, 3)
(28, 6, 1001, 3)
(28, 9, 1001, 3)
(28, 9, 1001, 3)
(28, 5, 1001, 3)
(28, 8, 1001, 3)
(28, 7, 1001, 3)
(28, 8, 1001, 3)
(28, 9, 1001, 3)
(28, 8, 1001, 3)
(28, 4, 1001, 3)
(28, 4, 1001, 3)
(28, 3, 1001, 3)
(28, 8, 1001, 3)
(28, 9, 1001, 3)
(28, 6, 1001, 3)
(28, 6, 1001, 3)
(28, 6, 1001, 3)
(28, 4, 1001, 3)
(28, 4, 1001, 3)
(28, 6, 1001, 3)
(28, 5, 1001, 3)
(28, 6, 1001, 3)
(28, 8, 1001, 3)
(28, 5, 1001, 3)
(28, 6, 1001, 3)
(28, 5, 1001, 3)
(28, 3, 1001, 3)
(28, 6, 1001, 3)
(28, 3, 1001, 3)
(28, 6, 1001, 3)
(28, 7, 1001, 3)
(28, 5, 1001, 3)
(28, 6, 1001, 3)
(28, 8, 1001, 3)
(28, 3, 1001, 3)
(28, 5, 1001, 3)
(28, 8, 1001, 3)
(28, 6, 1001, 3)
(28, 3, 1001, 3)
(28, 6, 100

In [18]:
data_nomarl["subject_ids"],data_stroke["subject_ids"]

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 

In [19]:
data_nomarl['n_trials'],data_stroke['n_trials']

(array([ 7,  9,  4,  6, 13,  8,  5,  9,  6,  7, 10,  5, 10,  4,  7,  4,  6,
         7,  6,  6,  9,  9,  5,  8,  7,  8,  9,  8,  4,  4,  3,  8,  9,  6,
         6,  6,  4,  4,  6,  5,  6,  8,  5,  6,  5,  3,  6,  3,  6,  7,  5,
         6,  8,  3,  5,  8,  6,  3,  6,  7,  5,  6,  7,  5,  6,  8,  8,  8,
         5,  5,  7,  3,  7,  4,  6,  6,  8,  7,  5,  6,  6,  5,  9,  6,  6,
         6,  8,  6,  4, 12,  7,  4,  6,  8,  5,  5,  4,  8,  6,  5,  6,  5,
         6,  3,  9,  6,  8,  4,  6,  5,  5,  4,  4,  3,  6,  8,  5,  5,  3,
         3,  7,  2,  4,  4,  5,  7,  3,  3,  4, 11,  4,  4,  5,  4,  7,  4,
         4,  5]),
 array([ 8,  9, 15,  7, 14,  7, 10,  6,  4,  9, 10,  3, 10,  6, 10,  3,  6,
        10, 11,  8,  8,  7,  6,  7,  8, 16,  5, 12, 12,  8,  8, 10, 13, 15,
         5,  6,  6,  6,  4, 12, 13, 10,  5,  4,  9, 13,  6,  6,  7,  4]))